export const ROUTES = {
  ROOT: {
    WELCOME: "/root/welcome",
    LOGIN: "/root/login",
    REGISTER: "/root/register",
    FORGOT_PASSWORD: "/root/forgot-password",
    RESET_PASSWORD: "/root/reset-password",
    VERIFY_EMAIL: "/root/verify-email",
    VERIFY_EMAIL_SUCCESS: "/root/verify-email-success",
    VERIFY_EMAIL_FAILED: "/root/verify-email-failed",
    VERIFY_EMAIL_EXPIRED: "/root/verify-email-expired",
  },
  ID: {
    HOME: "/root/(id)/(tabs)/home",
    SETTINGS: "/root/(id)/(tabs)/(settings)/profile-id",
    SETTINGS_PROFILE: "/root/(id)/(tabs)/(settings)/profile-id",
    SETTINGS_PASSWORD: "/root/(id)/(tabs)/(settings)/modify-password",
    SETTINGS_EMAIL: "/root/(id)/(tabs)/(settings)/modify-email",
    SETTINGS_PHONE: "/root/(id)/(tabs)/(settings)/modify-phone-number",
    SETTINGS_PHOTO: "/root/(id)/(tabs)/(settings)/modify-photo",
    SETTINGS_NOTIFICATIONS: "/root/(id)/(tabs)/(settings)/modify-notifications",
    SETTINGS_SECURITY: "/root/(id)/(tabs)/(settings)/modify-security",
    SETTINGS_PRIVACY: "/root/(id)/(tabs)/(settings)/modify-privacy",
  },
  PRO: {
    HOME: "/root/(pro)/(tabs)/home",
    SETTINGS: "/root/(pro)/(tabs)/(settings)/profile-pro",
    SETTINGS_PROFILE: "/root/(pro)/(tabs)/(settings)/profile-pro",
    SETTINGS_PASSWORD: "/root/(pro)/(tabs)/(settings)/modify-password",
    SETTINGS_EMAIL: "/root/(pro)/(tabs)/(settings)/modify-email",
    SETTINGS_PHONE: "/root/(pro)/(tabs)/(settings)/modify-phone-number",
    SETTINGS_PHOTO: "/root/(pro)/(tabs)/(settings)/modify-photo",
    SETTINGS_NOTIFICATIONS: "/root/(pro)/(tabs)/(settings)/modify-notifications",
    SETTINGS_SECURITY: "/root/(pro)/(tabs)/(settings)/modify-security",
    SETTINGS_PRIVACY: "/root/(pro)/(tabs)/(settings)/modify-privacy",
  },
};
